### PR TITLE
My Enumerable Methods

### PR DESCRIPTION
**Pull request by mahtsham**
Assignment 2 (Enumerable methods)
In this assignment, we have to build custom enumerable methods which will work the same as built-in enumerable methods. There are a total of 11 methods like my_each, my_all, my_any, and so on. This pull request has covered all of them.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
-----------
Hello!! @mahtsham :wave: you did an amazing job on this project congrats :muscle: :100: 
However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
---------------

- [ ] Write a meaningful title. Your title just is telling me that this pull request has only the linters. Kindly change it. E.g "My enumerable methods".
- [ ] Don't just copy and paste the description from the Odin project curriculum and paste it to the pull request description. You can write something like this :point_right:  "In this project, I add my own version of the enumerable methods" and a list of the enumerable methods "my_each, my_all? ....". [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) you can read how to write a meaningful description. 
- [ ] #my_each returns an Enumerator if no block is given. Instead is returning `no block given`
- [ ] Change the `length` inbuilt method to `size`. This `length` inbuilt method causes troubles with ranges (5..50).
- [ ] #my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self. Instead, doesn't return anything. 
- [ ] #my_select returns an array containing all elements of enum for which the given block returns a true value::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_select returns an enumerator if no block is given. Instead is returning `no block given`
- [ ] #my_all? returns false if the block returns false or nil::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_any? returns false if the block ever returns a value false or nil::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class. Instead is returning False. 
- [ ] #my_none? returns false if the block ever returns true for all elements::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_none? when no block or argument is given returns true only if none of the collection members is true. instead is returning False
- [ ] #my_count returns the number of items in enum through enumeration
- [ ] #my_map returns a new array with the results of running a given block once for every element in enum::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range. Is returning me an error "undefined method `[]' for 5..50"
- [ ] #my_inject when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method. is returning an error "no block given"
--------------
Make the required changes above :hammer_and_wrench: :point_up_2: and send it for another review. 
HAPPY CODING!!
MB5W4D

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Nice work so far on the enumerables project. You have more than 85% of the test passing.👏🏽 Great job. Just a few more tests to get all your enumerable methods working like the original ones.

- [ ] enumerables #my_each when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [ ] enumerables #my_each when a block is given when self is a range behaves like #each calls the given block once for each element in self
- [ ] enumerables #my_each when a block is given when self is a hash behaves like #each calls the given block once for each element in self
- [ ] enumerables #my_select returns an array containing all elements of enum for which the given block returns a true value::range
- [ ] enumerables #my_all? returns false if the block returns false or nil::range
- [ ] enumerables #my_any? returns false if the block ever returns a value false or nil::range
- [ ] enumerables #my_none? returns false if the block ever returns true for all elements::range
- [ ] enumerables #my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] enumerables #my_map returns a new array with the results of running a given block once for every element in enum::range

Please fix the above issues and submit for another code review. 👍🏽 
_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
----------------
Hello again @mahtsham :wave: You did an amazing job working on the required changes :100: :muscle: 
There is only one case that you have to check. See it below :eyes: :point_down: 
-------------------------

- [ ] #my_none? when no block or argument is given returns true only if none of the collection members is true. instead is returning False.
-------------------------
Make this change and send it again for another review :1st_place_medal: :100: 
HAPPY CODING !!
AngelicConcreteHypsilophodon-max-1mb

**Review by mke2111 — APPROVED** [review]
# **🎉 STATUS: APPROVED 🎉** 

## Hey @mahtsham, 👋🏽 
 **Congratulations 🥳 🥂 . The methods work just fine.**

**You may now merge to the develop branch and submit a project completion form. 👍🏽** 

## Cheers!! 🍹 

## Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by taiwo2 — COMMENTED** [review]
## STATUS: invalid 
@mahtsham   How are you , your submitted wrong PR for form project

**Review by rindrajosia — COMMENTED** [review]
Invalid 🔴 
@mahtsham you are submitted wrong PR for form project

**Review by BrianSammit — COMMENTED** [review]
STATUS. INVALID :yellow_circle: 
---------
Hello @mahtsham, you submitted the wrong PR for the form project.

**Review by GzimAsani — COMMENTED** [review]
# Hi @mahtsham, it seems that you again submitted the wrong PR. Therefore I need to invalidate again :red_circle:

**Pull request merged**
